---
# NOTE: the solr core is created by the containing playbook,
# at the time of installation (i.e. before this point),
# using functionality built into the solr role
# TODO: adjust to configure for multiple cores

- name: test variables
  debug:
    msg: "solr_core: {{ solr_core }}"

- name: symlink solr schema and config
  file:
    src: "{{ sufia_deploy_dir }}/solr/config/{{ item }}"
    dest: "/var/solr/data/{{ solr_core }}/conf/{{ item }}"
    state: link
    owner: "{{ solr_user }}"
    group: "{{ solr_user }}"
    force: yes
  with_items:
    - "schema.xml"
    - "solrconfig.xml"
  become: true
  notify: restart solr

# NOTE: this will overwrite the solr.yml file created when building with RAILS_ENV=development
- name: template solr.yml
  template:
    src: "solr.yml.j2"
    dest: "{{ sufia_deploy_dir }}/config/solr.yml"
    owner: "{{ sufia_app_user }}"
    group: "{{ sufia_app_user }}"
  become: true
  notify: restart solr
