---
  # TODO: see about accessing from solr role (perhaps if both roles were called from same playbook?)
- name: restart solr
  service:
    name: solr
    state: restarted
  become: true

# FIXME: using sufia_mode test to avoid trying to restart apache when it isn't being used
# since notify apparently cannot be conditional. this approach works,
# but seems fragile or at least inelegant.
- name: restart apache
  service:
    name: "{{ apache_service }}"
    enabled: true
    state: restarted
  become: true
  when: sufia_mode == "prod_like"

- name: shim ruby executables
  command: "rbenv rehash"
  when: ansible_os_family == 'Darwin'
